all: client6
client1:client1.cpp
	g++ -o $@ $& -std=c++11

client2:client2.cpp
	g++ -o $@ $& -std=c++11

client3:client3.cpp
	g++ -o $@ $& -std=c++11

client4:client4.cpp
	g++ -o $@ $& -std=c++11

client5:client5.cpp
	g++ -o $@ $& -std=c++11

client6:client6.cpp
	g++ -o $@ $& -std=c++11

server:server.cc
	g++ -o $@ $& -std=c++11

client:tcp_cli.cc
	g++ -o $@ $& -std=c++11

tcp_srv:tcp_srv.cc
	g++ -o $@ $& -std=c++11
